# Generated by Django 4.0 on 2021-12-15 12:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=100, null=True)),
                ('no_of_spaces', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name_plural': 'Parking Spaces',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=100)),
                ('start_period', models.DateTimeField()),
                ('end_period', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('ticket', models.CharField(max_length=7)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: (+7|8) 960 xxx-xx-xx ', regex='^(\\+?7|8)\\d{10}$')])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.parking_space')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
