# Generated by Django 4.0 on 2021-12-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_space',
            name='no_of_spaces',
            field=models.IntegerField(default=2),
        ),
    ]
